package pl.bka.dtb.model

class NoPossibilityOfMappingLegsConnectionsToConsecutiveTracks extends Exception
class TrackGroupsOfLengthLargerThanTwoAreNotSupported extends Exception
class TooManyCables extends Exception


