package pl.bka.model

class NoPossibilityOfMappingLegsConnectionsToConsecutiveTracks extends Exception
class TrackGroupsOfLengthLargerThanTwoAreNotSupported extends Exception
class TooManyCables extends Exception


